@AT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWF0IjoxNzU5ODQxMDE1LCJleHAiOjE3NTk4NDE5MTV9.cM3gAXvOX7XPR3bcH2gxURXERK4VzU9OrJLww94LUKo

#? Create attendance_record and update check in details
post http://localhost:8000/api/attendance/create-attendance-record
Content-Type: application/json

{
    "username": "test1",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",
    "record_type": "check_in",
    "image_capture_date": "2025-10-07T12:34:33.205Z",
    "update_code": 0
}

###
post http://localhost:8000/api/attendance/create-attendance-record
Content-Type: application/json

{
    "username": "test1",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",
    "record_type": "check_out",
    "image_capture_date": "2025-10-07T12:34:33.205Z",
    "update_code": 2
}

#? update check out details on attendance_record

# "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",