@AT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWF0IjoxNzU5ODQxMDE1LCJleHAiOjE3NTk4NDE5MTV9.cM3gAXvOX7XPR3bcH2gxURXERK4VzU9OrJLww94LUKo


# update code(create_attendance_records):
# 0 - Create a new attendance record
# 1 - Update check-in fields on existing record
# 2 - Update check-out fields on existing record
#? Create attendance_record and update check in details
post http://localhost:8000/api/attendance/create-attendance-record
Content-Type: application/json

{
    "username": "test1",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",
    "record_type": "check_in",
    "image_capture_date": "2025-10-17T12:34:33.205Z",
    "selected_date": "2025-10-17T12:34:33.205Z",
    "update_code": 0
}

###
post http://localhost:8000/api/attendance/create-attendance-record
Content-Type: application/json

{
    "username": "test1",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",
    "record_type": "check_out",
    "image_capture_date": "2025-10-17T12:34:33.205Z",
    "selected_date": "2025-10-17T08:03:55.618Z",
    "update_code": 2
}

# "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",

###

#? update check out details on attendance_record

# update code:
#   0 - update status to pass
#   1 - update status to fail
#   2 - revert status to pending

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json

{
    "id": 34,
    "attendance_date": "2025-10-09",
    "update_code": 2
}

###

#? get attendance records
get http://localhost:8000/api/attendance/get-attendance-record
Content-Type: application/json

{}


###
#? reset attendance records

patch http://localhost:8000/api/attendance/reset-attendance-record
Content-Type: application/json

{
    "id": 32
}

###
#? reset attendance records

get http://localhost:8000/api/attendance/get-attendance-record
Content-Type: application/json

{
    "request_code": 1,
    "user_id": 2
}