@AT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJ0ZXN0MSIsImlhdCI6MTc2NjY2MjcyNiwiZXhwIjoxNzY2NjYzNjI2fQ.Jjd0dMvHj6j1NI5lkh7CxaN9fiOAl8G2TR-kW59Ylwk


# update code(create_attendance_records):
# 0 - Create a new attendance record
# 1 - Update check-in fields on existing record
# 2 - Update check-out fields on existing record
#? Create attendance_record and update check in details
post http://localhost:8000/api/attendance/create-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username": "test1",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",
    "record_type": "check_in",
    "image_capture_date": "2025-10-17T12:34:33.205Z",
    "selected_date": "2025-10-17T12:34:33.205Z",
    "update_code": 0
}

###
post http://localhost:8000/api/attendance/create-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username": "test9",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",
    "record_type": "check_out",
    "image_capture_date": "2025-11-17T08:34:33.205Z",
    "selected_date": "2025-11-16T08:03:55.618Z",
    "update_code": 2
}

# "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",

###

#? update check out details on attendance_record

# update code:
#   0 - update status to pass
#   1 - update status to fail
#   2 - revert status to pending
#   3 - update schedule attendance records 

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "id": "54",
    "attendance_date": "2025-12-25",
    "update_code": 1
}

###
#? update schedule attendance records

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "id": 40,
    "attendance_date": "2025-10-13",
    "update_code": 3,
    "u_sched_in": "08:00",
    "u_sched_out": "16:00"
}

###
#? update single/multiple ot hours

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "idArr": [1, 2],
    "ot_hours": 3,
    "update_code": 4
}

###

#? get attendance records
post http://localhost:8000/api/attendance/get-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "request_code": 0
}


###
#? reset attendance records

patch http://localhost:8000/api/attendance/reset-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "id": 32
}

###
#? get attendance records by id

post http://localhost:8000/api/attendance/get-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "request_code": 1,
    "user_id": 2,
    "selected_date": "2025-10-10"
}