@AT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Q0IiwiaWF0IjoxNzU1NDM0NDA3LCJleHAiOjE3NTU0MzUzMDd9.smM-SfoGyMfbx2qwvY07CgdW0kxth2ikFyCaGP3Xs5U


post http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username":"test4",
    "password":"12345"
}

###

post http://localhost:8000/api/auth/logout
Content-Type: application/json

###
get http://localhost:8000/api/auth/profile
Authorization: Bearer {{AT}}

###

post http://localhost:8000/api/auth/refresh

###

post http://localhost:8000/api/users/create-user
Content-Type: application/json

# {
#     "username":"admin",
#     "password":"admin",
#     "email":"admin@gmail.com",
#     "first_name":"admin",
#     "middle_name":"admin",
#     "last_name":"admin",
#     "gender":"male",
#     "role":"admin",
#     "user_profile_image_url":"test1 profile image url"
# }

# {
#     "username":"test1",
#     "password":"test1",
#     "email":"test1@gmail.com",
#     "first_name":"test1 first name",
#     "middle_name":"test1 middle name",
#     "last_name":"test1 last name",
#     "gender":"male",
#     "user_profile_image_url":"test1 profile image url"
# }

# no password 
{
    "username":"test4",
    "email":"test4@gmail.com",
    "first_name":"test4 first name",
    "middle_name":"test4 middle name",
    "last_name":"test4 last name",
    "gender":"male",
    "user_profile_image_url":"test4 profile image url"
}

###

get http://localhost:8000/api/users/get-all-users

###

post http://localhost:8000/api/users/update-user
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username":"test1",
    "first_name":"test1 first name"
}

###
post http://localhost:8000/api/users/delete-user
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username":"test3"
}

###

post http://localhost:8000/api/users/get-user-by-username
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username":"test1"
}
