@AT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJ0ZXN0MSIsImlhdCI6MTc2MzM4MjEwNywiZXhwIjoxNzYzMzgzMDA3fQ.GlX8RESsq9wbIrJ8silwEhZ9nznA2nSSX1uQBxmv4ko


post http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username":"test1",
    "password":"test1"
}

###

post http://localhost:8000/api/auth/logout
Content-Type: application/json

###
get http://localhost:8000/api/auth/profile
Authorization: Bearer {{AT}}

###

post http://localhost:8000/api/auth/refresh

###

post http://localhost:8000/api/users/create-user
Authorization: Bearer {{AT}}
Content-Type: application/json

# {
#     "username":"admin",
#     "password":"admin",
#     "email":"admin@gmail.com",
#     "first_name":"admin",
#     "middle_name":"admin",
#     "last_name":"admin",
#     "gender":"male",
#     "role":"admin",
#     "user_profile_image_url":"test1 profile image url"
# }

{
    "username":"test8",
    "password":"test8",
    "email":"test8@gmail.com",
    "first_name":"test8",
    "middle_name":"test8",
    "last_name":"test8",
    "gender":"male",
    "user_profile_image_url":"test8 profile image url",
    "u_sched_in": "08:18",
    "u_sched_out": "20:18"
}

# no password 
# {
#     "username":"test4",
#     "email":"test4@gmail.com",
#     "first_name":"test4 first name",
#     "middle_name":"test4 middle name",
#     "last_name":"test4 last name",
#     "gender":"male",
#     "user_profile_image_url":"test4 profile image url"
# }

###

get http://localhost:8000/api/users/get-all-users
Authorization: Bearer {{AT}}

###

post http://localhost:8000/api/users/update-user
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username":"test1",
    "first_name":"test1 first name"
}

###
post http://localhost:8000/api/users/delete-user
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username":"test3"
}

###

post http://localhost:8000/api/users/get-user-by-username
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username":"test1"
}
