@AT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoidGVzdDQiLCJpYXQiOjE3NTE3OTk4ODMsImV4cCI6MTc1MTc5OTg5M30.ymDqN0X-ijTHDR0iyNvLaqOhcG7HFhebWWXrj-AdQgE

post http://localhost:8000/api/users/create-user
Content-Type: application/json

{
    "username":"test4",
    "password":"test4"
}

# {
#     "username":"test4",
#     "password":"test4"
# }

###

post http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username":"test4",
    "password":"test4"
}

###

post http://localhost:8000/api/auth/logout
Content-Type: application/json

###
get http://localhost:8000/api/auth/profile
Authorization: Bearer {{AT}}

###

post http://localhost:8000/api/auth/refresh