@AT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJ0ZXN0MSIsImlhdCI6MTc2OTI1NzIxNiwiZXhwIjoxNzY5MjU4MTE2fQ.g4aPEJ9t0oBi6e61GjUmKnHs1IM5XAZXnHyuLw9nJm0

post http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username":"test1",
    "password":"test1"
}

###
# update code(create_attendance_records):
# 0 - Create a new attendance record
# 1 - Update check-in fields on existing record
# 2 - Update check-out fields on existing record
#? Create attendance_record and update check in details
post http://localhost:8000/api/attendance/create-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username": "test1",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",
    "record_type": "check_in",
    "image_capture_date": "2025-10-17T12:34:33.205Z",
    "selected_date": "2025-10-17T12:34:33.205Z",
    "update_code": 0
}

###
post http://localhost:8000/api/attendance/create-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "username": "test9",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",
    "record_type": "check_out",
    "image_capture_date": "2025-11-17T08:34:33.205Z",
    "selected_date": "2025-11-16T08:03:55.618Z",
    "update_code": 2
}

# "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0n2dUPE7rmcyiWIArIrInNjSuHw5Wk9gJEw&s",

###

#? update check out details on attendance_record

# update code:
# 0 - update status to pass
# 1 - update status to fail
# 2 - revert status to pending (delete images and reset check-in/out data)
# 3 - update/modify attendance record schedule
# 4 - update overtime (multiple or single)
# 5 - update/modify attendance record check in & out and overtime

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "id": "35",
    "attendance_date": "2025-10-10",
    "update_code": 1
}

###

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "id": "58",
    "attendance_date": "2025-12-29",
    "update_code": 2
}

###
#? update schedule attendance records (CODE 3)

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "update_code": 3,
    "usersIds": [2, 3],
    "dateFrom": "2025-12-15",
    "dateTo": "2025-12-29",
    "u_sched_in": "08:00",
    "u_sched_out": "16:00"
}

###
#? update single/multiple ot hours (CODE 4)

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "idArr": [4,5,6,7],
    "ot_hours": 2,
    "update_code": 4
}

###
#? update/modify attendance record check in & out and overtime (CODE 5)

patch http://localhost:8000/api/attendance/audit-attendance-update
Content-Type: application/json
Authorization: Bearer {{AT}}

{    
    "update_code": 5,
    "attendance_date": "2025-11-05",
    "user_id": 2,
    "id": 47,
    "check_in_time": "2025-12-16T12:34:33.205Z",
    "check_out_time": "2025-12-16T12:54:33.205Z",
    "ot_hours": 3
}

###

#? get attendance records
post http://localhost:8000/api/attendance/get-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "request_code": 0
}


###
#? reset/revert attendance records

# patch http://localhost:8000/api/attendance/reset-attendance-record
# Content-Type: application/json
# Authorization: Bearer {{AT}}

# {
#     "id": 32
# }

###
#? get attendance records by id

post http://localhost:8000/api/attendance/get-attendance-record
Content-Type: application/json
Authorization: Bearer {{AT}}

{
    "request_code": 2,
    "user_id": 2,
    "selected_date": "2025-10-10"
}